export const screens = {
  auth: 'Auth',
  authLoading: 'AuthLoading',
  app: 'App',
  home: 'Home',
  detail: 'Detail',
  signIn: 'SignIn',
  signUp: 'SignUp',
  welcome: 'Welcome',
  drawer: 'DrawerNavigator',
  settings: 'Settings',
  profile: 'Profile',
  language: 'LanguageSelector',
  dashboard: 'Dashboard',
  dashboardTabNavigator: 'DashboardTabNavigator',
};
